import LegalLayout from "@/components/estroc/LegalLayout";

export default function Terms() {
  return (
    <LegalLayout title="Terms & Conditions" updated="September 2026">
      <section>
        <p>
          These terms govern your use of{" "}
          <span className="text-zinc-200">estroc-one.vercel.app</span>. By
          browsing the site or submitting a project enquiry, you agree to them.
          If you don't agree, please don't use the site.
        </p>
      </section>

      <section>
        <h2>Use of this website</h2>
        <p>
          This site is provided to showcase ESTROC's work and let visitors get
          in touch about a project. You agree not to misuse it — no attempts to
          disrupt the site, scrape it at scale, or submit the enquiry form or
          chat widget with spam, malicious content or false information.
        </p>
      </section>

      <section>
        <h2>Project engagements</h2>
        <p>
          Submitting a project brief through this site — via the form or the AI
          chat widget — is an enquiry, not a contract. Any actual engagement,
          scope, pricing and timeline is agreed separately in writing between
          ESTROC and the client before work begins.
        </p>
      </section>

      <section>
        <h2>Intellectual property</h2>
        <p>
          The ESTROC name, logo, and the content, design and code of this
          website belong to ESTROC unless stated otherwise. Project names,
          screenshots and links shown under "Our Work" belong to their
          respective owners and are shown to illustrate work ESTROC has built.
        </p>
      </section>

      <section>
        <h2>The AI chat widget</h2>
        <p>
          The ESTROC AI widget is an automated assistant intended to answer
          general questions about ESTROC and help capture a project brief. Its
          responses are generated by an AI model and, while we keep it scoped to
          accurate information about ESTROC, they should not be treated as a
          binding quote, commitment or legal advice.
        </p>
      </section>

      <section>
        <h2>No warranties</h2>
        <p>
          This website is provided "as is." We work to keep it accurate and
          available, but we don't guarantee it will be error-free, uninterrupted,
          or fit for a particular purpose.
        </p>
      </section>

      <section>
        <h2>Limitation of liability</h2>
        <p>
          To the extent permitted by law, ESTROC is not liable for any indirect,
          incidental or consequential loss arising from your use of this
          website. This does not limit liability arising from a separately
          agreed client contract, which is governed by its own terms.
        </p>
      </section>

      <section>
        <h2>Governing law</h2>
        <p>
          These terms are governed by the laws of India. Any dispute arising
          from your use of this website falls under the jurisdiction of Indian
          courts.
        </p>
      </section>

      <section>
        <h2>Changes to these terms</h2>
        <p>
          We may update these terms as the site evolves. The "last updated" date
          above reflects the most recent revision. Continued use of the site
          after a change means you accept the updated terms.
        </p>
      </section>

      <section>
        <h2>Contact</h2>
        <p>
          Questions about these terms — <a href="mailto:hello@estroc.com">hello@estroc.com</a>.
        </p>
      </section>
    </LegalLayout>
  );
}
